name: Build

on:
  pull_request:
    branches: [main]

jobs:
  base:
    uses: ./.github/workflows/build-image.yml
    with:
      target: base
    permissions:
      contents: read
      packages: read

  java-node:
    needs: base
    uses: ./.github/workflows/build-image.yml
    with:
      target: java-node
    permissions:
      contents: read
      packages: read
