name: Release

on:
  push:
    branches: [main]
    tags: ['v*']

jobs:
  release:
    uses: ./.github/workflows/build-image.yml
    with:
      push: true
    permissions:
      contents: read
      packages: write
